### ISSUE TITLE
Find by name bug

### ISSUE THREAD

**Issue by InfinityTwo** [AY2425S1-CS2103T-T10-2/tp#157]
When you add numbers to the end of the name in find, it shows by wildcard or something?

Example if you have the following data set
![image](https://github.com/user-attachments/assets/f5724d2c-b5d7-45d1-be5e-9de2715c352a)

and if you do ```find e n/John Doe4```, it shows all 4 results, which seems incorrect

**Comment by jevan13** [comment]
@InfinityTwo Hi, the Find command searches each word individually.

For example, inputting "find e n/John Doe4" returns all employees with either "John" or "Doe4" in their name, giving the 4 results.
