### ISSUE TITLE
Date range for CED can be unrealistic

### ISSUE THREAD

**Issue by InfinityTwo** [AY2425S1-CS2103T-T10-2/tp#165]
https://en.wikipedia.org/wiki/List_of_oldest_companies

Since the oldest recorded company still active only started in year 578, it's not exactly right to allow years below then, including negative years
![image](https://github.com/user-attachments/assets/40d49f33-e796-461e-8216-ff1cd87ce38c)

**Comment by thortol** [comment]
Great point! However I think its safer to be flexible and allow any valid year rather than be overzealous with input validation.
