### ISSUE TITLE
Edit command UI different order

### ISSUE THREAD

**Issue by jevan13** [AY2425S1-CS2103T-T10-2/tp#166]
![Screenshot 2024-11-02 at 1 24 24 AM](https://github.com/user-attachments/assets/b3d06f71-051c-477c-bcb7-2b292a423b43)

Status message shows email before address whereas the person's information shows email after address

**Comment by thortol** [comment]
This is a bug that exists in AB3 I think its small enough that it does not matter if we have extra time can consider fixing it.
![image](https://github.com/user-attachments/assets/34a189cc-0e56-4189-b432-de5dd14dc8c6)

**Comment by jevan13** [comment]
Noted, thanks!
