### ISSUE TITLE
Edit Command Status Message Incomplete

### ISSUE THREAD

**Issue by jevan13** [AY2425S1-CS2103T-T10-2/tp#168]
![Screenshot 2024-11-02 at 1 18 46 AM](https://github.com/user-attachments/assets/543c3fdd-aba6-4c99-ace9-22e023ceedd8)

Status message should show the entire information about the person, but is cut off now. 
Causes inconvenience when using commands like "edit 10 d/IT", and user has to scroll down to the person to check if department has been editted.
No issues for "edit 10 n/John" as user can see the updated name in the status message.

**Comment by thortol** [comment]
For the cut off issue the user can scroll down in the edit message to see all the fields that were edited.
![image](https://github.com/user-attachments/assets/989d4578-46c4-486a-ae24-94b165e06feb)

**Comment by jevan13** [comment]
I see. Thank you for the clarification!
