### ISSUE TITLE
[PE-D][Tester C] Can add phone numbers with more than 8 digits

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T10-2/tp#237]
![Screenshot 2024-11-08 164652.png](https://raw.githubusercontent.com/obrona/ped/main/files/0ee48fe8-6f6e-4237-991b-b652f3897703.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: obrona/ped#2

**Comment by KiKuasaurus** [comment]
![image](https://github.com/user-attachments/assets/f32621ed-ae2b-465f-ae63-20e332245076)
